//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTextInputLayoutPlugin\src\main\java\com\ashera\textinputlayout\TextInputLayoutPlugin.java
//

#include "EditTextImpl.h"
#include "J2ObjC_source.h"
#include "TextInputLayoutImpl.h"
#include "TextInputLayoutPlugin.h"
#include "WidgetFactory.h"


@implementation ASTextInputLayoutPlugin

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  ASTextInputLayoutPlugin_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (void)initPlugin {
  ASTextInputLayoutPlugin_initPlugin();
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x9, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(initPlugin);
  #pragma clang diagnostic pop
  static const J2ObjcClassInfo _ASTextInputLayoutPlugin = { "TextInputLayoutPlugin", "com.ashera.textinputlayout", NULL, methods, NULL, 7, 0x1, 2, 0, -1, -1, -1, -1, -1 };
  return &_ASTextInputLayoutPlugin;
}

@end

void ASTextInputLayoutPlugin_init(ASTextInputLayoutPlugin *self) {
  NSObject_init(self);
}

ASTextInputLayoutPlugin *new_ASTextInputLayoutPlugin_init() {
  J2OBJC_NEW_IMPL(ASTextInputLayoutPlugin, init)
}

ASTextInputLayoutPlugin *create_ASTextInputLayoutPlugin_init() {
  J2OBJC_CREATE_IMPL(ASTextInputLayoutPlugin, init)
}

void ASTextInputLayoutPlugin_initPlugin() {
  ASTextInputLayoutPlugin_initialize();
  ASWidgetFactory_register__WithASIWidget_(new_ASTextInputLayoutImpl_init());
  ASWidgetFactory_register__WithASIWidget_(new_ASEditTextImpl_initWithNSString_withNSString_(@"com.google.android.material.textfield.TextInputEditText", @"com.google.android.material.textfield.TextInputEditText"));
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ASTextInputLayoutPlugin)
