//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTextInputLayoutPlugin\src\main\java\com\ashera\textinputlayout\TextInputLayoutPlugin.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TextInputLayoutPlugin")
#ifdef RESTRICT_TextInputLayoutPlugin
#define INCLUDE_ALL_TextInputLayoutPlugin 0
#else
#define INCLUDE_ALL_TextInputLayoutPlugin 1
#endif
#undef RESTRICT_TextInputLayoutPlugin

#if !defined (ASTextInputLayoutPlugin_) && (INCLUDE_ALL_TextInputLayoutPlugin || defined(INCLUDE_ASTextInputLayoutPlugin))
#define ASTextInputLayoutPlugin_

@interface ASTextInputLayoutPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutPlugin)

FOUNDATION_EXPORT void ASTextInputLayoutPlugin_init(ASTextInputLayoutPlugin *self);

FOUNDATION_EXPORT ASTextInputLayoutPlugin *new_ASTextInputLayoutPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutPlugin *create_ASTextInputLayoutPlugin_init(void);

FOUNDATION_EXPORT void ASTextInputLayoutPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutPlugin)

@compatibility_alias ComAsheraTextinputlayoutTextInputLayoutPlugin ASTextInputLayoutPlugin;

#endif

#pragma pop_macro("INCLUDE_ALL_TextInputLayoutPlugin")
