//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTextInputLayoutPlugin\src\main\java\com\ashera\textinputlayout\TextInputLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TextInputLayoutImpl")
#ifdef RESTRICT_TextInputLayoutImpl
#define INCLUDE_ALL_TextInputLayoutImpl 0
#else
#define INCLUDE_ALL_TextInputLayoutImpl 1
#endif
#undef RESTRICT_TextInputLayoutImpl

#if !defined (ASTextInputLayoutImpl_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl))
#define ASTextInputLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

#define RESTRICT_FormElement 1
#define INCLUDE_ASFormElement 1
#include "FormElement.h"

@class ASTextInputLayoutImpl_TextInputLayoutBean;
@class ASTextInputLayoutImpl_TextInputLayoutCommandBuilder;
@class ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder;
@class ASTextInputLayoutImpl_TextInputLayoutParamsBean;
@class ASWidgetAttribute;
@class IOSClass;
@protocol ASHasWidgets;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTextInputLayoutImpl : ASBaseHasWidgets < ASFormElement >
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)focus;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (ASTextInputLayoutImpl_TextInputLayoutBean *)getBean;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)getBuilder;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (id<ASHasWidgets>)getCompositeLeafWithASIWidget:(id<ASIWidget>)w;

- (ASTextInputLayoutImpl_TextInputLayoutParamsBean *)getParamsBean;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)getParamsBuilder;

- (id)getPluginWithNSString:(NSString *)plugin;

- (NSString *)getTextEntered;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (jboolean)isViewVisible;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)resetError;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setEndIconInternalWithId:(id)objValue
                     withBoolean:(jboolean)skipConvert;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

- (void)showErrorWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl)

inline NSString *ASTextInputLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTextInputLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTextInputLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASTextInputLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTextInputLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTextInputLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_init(ASTextInputLayoutImpl *self);

FOUNDATION_EXPORT ASTextInputLayoutImpl *new_ASTextInputLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl *create_ASTextInputLayoutImpl_init(void);

FOUNDATION_EXPORT void ASTextInputLayoutImpl_initWithNSString_(ASTextInputLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASTextInputLayoutImpl *new_ASTextInputLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl *create_ASTextInputLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASTextInputLayoutImpl_initWithNSString_withNSString_(ASTextInputLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASTextInputLayoutImpl *new_ASTextInputLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl *create_ASTextInputLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl)

@compatibility_alias ComAsheraTextinputlayoutTextInputLayoutImpl ASTextInputLayoutImpl;

#endif

#if !defined (ASTextInputLayoutImpl_EndIconMode_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_EndIconMode))
#define ASTextInputLayoutImpl_EndIconMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTextInputLayoutImpl_EndIconMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_EndIconMode)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_EndIconMode_init(ASTextInputLayoutImpl_EndIconMode *self);

FOUNDATION_EXPORT ASTextInputLayoutImpl_EndIconMode *new_ASTextInputLayoutImpl_EndIconMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_EndIconMode *create_ASTextInputLayoutImpl_EndIconMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_EndIconMode)

#endif

#if !defined (ASTextInputLayoutImpl_BoxBackgroundMode_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_BoxBackgroundMode))
#define ASTextInputLayoutImpl_BoxBackgroundMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTextInputLayoutImpl_BoxBackgroundMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_BoxBackgroundMode)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_BoxBackgroundMode_init(ASTextInputLayoutImpl_BoxBackgroundMode *self);

FOUNDATION_EXPORT ASTextInputLayoutImpl_BoxBackgroundMode *new_ASTextInputLayoutImpl_BoxBackgroundMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_BoxBackgroundMode *create_ASTextInputLayoutImpl_BoxBackgroundMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_BoxBackgroundMode)

#endif

#if !defined (ASTextInputLayoutImpl_TextInputLayoutExt_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_TextInputLayoutExt))
#define ASTextInputLayoutImpl_TextInputLayoutExt_

#define RESTRICT_LinearLayout 1
#define INCLUDE_ADLinearLayout 1
#include "LinearLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADRect;
@class ADView;
@class ASTextInputLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASTextInputLayoutImpl_TextInputLayoutExt : ADLinearLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASTextInputLayoutImpl:(ASTextInputLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_TextInputLayoutExt)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_TextInputLayoutExt_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl_TextInputLayoutExt *self, ASTextInputLayoutImpl *outer$);

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutExt *new_ASTextInputLayoutImpl_TextInputLayoutExt_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutExt *create_ASTextInputLayoutImpl_TextInputLayoutExt_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_TextInputLayoutExt)

#endif

#if !defined (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_TextInputLayoutCommandBuilder))
#define ASTextInputLayoutImpl_TextInputLayoutCommandBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandBuilder 1
#include "ViewGroupImpl.h"

@class ASTextInputLayoutImpl;

@interface ASTextInputLayoutImpl_TextInputLayoutCommandBuilder : ASViewGroupImpl_ViewGroupCommandBuilder

#pragma mark Public

- (instancetype)initWithASTextInputLayoutImpl:(ASTextInputLayoutImpl *)outer$;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)addAllModelWithId:(id)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)addModelByIndexWithId:(id)arg0
                                                                        withId:(id)arg1;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)addModelWithId:(id)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)executeWithBoolean:(jboolean)setter;

- (id)getBoxStrokeErrorColor;

- (id)getCounterMaxLength;

- (id)getCounterOverflowTextColor;

- (id)getCounterTextColor;

- (id)getEndIconDrawable;

- (id)getEndIconMode;

- (id)getErrorIconDrawable;

- (id)getHint;

- (id)getHintTextColor;

- (id)getPlaceholderTextColor;

- (id)getPrefixTextColor;

- (id)getStartIconDrawable;

- (id)getSuffixTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)invalidate;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)notifyDataSetChangedWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)refreshUiFromModelWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)removeModelAtIndexWithInt:(jint)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)removeModelByIdWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)requestLayout;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)reset;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setAddStatesFromChildrenWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setAlphaWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setAsDragSourceWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setAttributeUnderTestWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBackgroundRepeatWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBackgroundTintModeWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBackgroundTintWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBackgroundWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxBackgroundColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxBackgroundModeWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxCornerRadiusBottomEndWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxCornerRadiusBottomStartWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxCornerRadiusTopEndWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxCornerRadiusTopStartWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxPaddingWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxStrokeColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxStrokeErrorColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setBoxStrokeWidthWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setChildXmlWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setClickableWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setClipChildrenWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setClipToPaddingWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setContentDescriptionWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCounterEnabledWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCounterMaxLengthWithInt:(jint)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCounterOverflowTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCounterOverflowTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCounterTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCounterTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCustomErrorMessageKeysWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setCustomErrorMessageValuesWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setDuplicateParentStateWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setEnabledWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setEndIconDrawableWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setEndIconModeWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setEndIconOnClickWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setEndIconOnLongClickWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setEndIconVisibleWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorEnabledWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorIconDrawableWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorIconOnClickWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorIconOnLongClickWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorStyleWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setErrorTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setFocusableWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setForegroundGravityWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setForegroundRepeatWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setForegroundTintModeWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setForegroundTintWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setForegroundWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHelperTextWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHelperTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHelperTextEnabledWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHelperTextTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHintWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHintEnabledWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHintTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setHintTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIdWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setInvalidateOnFrameChangeWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAccessibilityHintWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAccessibilityIgnoresInvertColorsWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAccessibilityLabelWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAccessibilityTraitsWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAccessibilityValueWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAlphaWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosAutoresizesSubviewsWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosBackgroundColorWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosClearsContextBeforeDrawingWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosClipsToBoundsWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosContentScaleFactorWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosInsetsLayoutMarginsFromSafeAreaWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosIsAccessibilityElementWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosIsExclusiveTouchWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosIsHiddenWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosIsMultipleTouchEnabledWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosIsOpaqueWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosIsUserInteractionEnabledWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosLargeContentImageWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosLargeContentTitleWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosLayerBorderColorWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosLayerBorderWidthWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosLayerCornerRadiusWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosLayerMasksToBoundsWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosPreservesSuperviewLayoutMarginsWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosRestorationIdentifierWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosScalesLargeContentImageWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosShowsLargeContentViewerWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosTagWithInt:(jint)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosTintColorWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setIosTranslatesAutoresizingMaskIntoConstraintsWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setKeepScreenOnWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setLayoutDirectionWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setLayoutModeWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setListitemWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setLongClickableWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setMaxHeightWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setMaxWidthWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setMinHeightWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setMinWidthWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelDescPathWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelForWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelIdPathWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelParamWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelPojoToUiParamsWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelPojoToUiWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelSyncEventsWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelUiToPojoEventIdsWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setModelUiToPojoWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnChildViewAddedWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnChildViewRemovedWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnClickWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnDragWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnKeyWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnLongClickWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnSwipedWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOnTouchWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setOutsideTouchableWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingBottomWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingEndWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingHorizontalWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingLeftWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingRightWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingStartWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingTopWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingVerticalWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPaddingWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPlaceholderTextWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPlaceholderTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPrefixTextWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPrefixTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setPrefixTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setRotationWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setRotationXWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setRotationYWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setScaleXWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setScaleYWithFloat:(jfloat)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setSelectedWithBoolean:(jboolean)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setStartIconDrawableWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setStartIconOnClickWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setStartIconOnLongClickWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setStartIconVisibleWithBoolean:(jboolean)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setStyleWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setSuffixTextWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setSuffixTextAppearanceWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setSuffixTextColorWithNSString:(NSString *)value;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTextAlignmentWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTextDirectionWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTransformPivotXWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTransformPivotYWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTranslationXWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTranslationYWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setTranslationZWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_maxlengthWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_maxWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_minlengthWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_minWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_patternWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_requiredWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setV_typeWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setValidationErrorDisplayTypeWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setValidationWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setVisibilityWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)setZIndexWithInt:(jint)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetAddStatesFromChildren;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetAlpha;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetBackground;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetBackgroundTint;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetBackgroundTintMode;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetBoxStrokeErrorColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetClickable;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetClipChildren;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetClipToPadding;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetContentDescription;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetCounterMaxLength;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetCounterOverflowTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetCounterTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetDuplicateParentState;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetEnabled;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetEndIconDrawable;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetEndIconMode;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetErrorIconDrawable;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetFocusable;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetForeground;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetForegroundGravity;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetForegroundTint;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetForegroundTintMode;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetHint;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetHintTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetId;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAccessibilityHint;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAccessibilityIgnoresInvertColors;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAccessibilityLabel;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAccessibilityTraits;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAccessibilityValue;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAlpha;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosAutoresizesSubviews;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosBackgroundColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosClearsContextBeforeDrawing;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosClipsToBounds;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosContentScaleFactor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosInsetsLayoutMarginsFromSafeArea;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsAccessibilityElement;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsExclusiveTouch;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsFocused;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsHidden;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsMultipleTouchEnabled;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsOpaque;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosIsUserInteractionEnabled;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosLargeContentImage;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosLargeContentTitle;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosPreservesSuperviewLayoutMargins;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosRestorationIdentifier;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosScalesLargeContentImage;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosShowsLargeContentViewer;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosTag;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosTintColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetIosTranslatesAutoresizingMaskIntoConstraints;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetKeepScreenOn;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetLayoutDirection;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetLayoutMode;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetLongClickable;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetMaxHeight;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetMaxWidth;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetMinHeight;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetMinWidth;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetModelDescPath;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetModelIdPath;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetModelParam;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetModelPojoToUi;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetModelSyncEvents;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetModelUiToPojo;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPaddingBottom;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPaddingEnd;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPaddingLeft;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPaddingRight;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPaddingStart;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPaddingTop;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPlaceholderTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetPrefixTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetRotation;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetRotationX;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetRotationY;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetScaleX;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetScaleY;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetSelected;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetStartIconDrawable;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetSuffixTextColor;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTextAlignment;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTextDirection;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTransformPivotX;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTransformPivotY;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTranslationX;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTranslationY;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetTranslationZ;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetValidateForm;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)tryGetVisibility;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)updateModelDataWithNSString:(NSString *)arg0
                                                                              withId:(id)arg1;

- (ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *)validateFormWithNSString:(NSString *)arg0;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_TextInputLayoutCommandBuilder)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_TextInputLayoutCommandBuilder_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *self, ASTextInputLayoutImpl *outer$);

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *new_ASTextInputLayoutImpl_TextInputLayoutCommandBuilder_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutCommandBuilder *create_ASTextInputLayoutImpl_TextInputLayoutCommandBuilder_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_TextInputLayoutCommandBuilder)

#endif

#if !defined (ASTextInputLayoutImpl_TextInputLayoutBean_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_TextInputLayoutBean))
#define ASTextInputLayoutImpl_TextInputLayoutBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupBean 1
#include "ViewGroupImpl.h"

@class ASTextInputLayoutImpl;
@protocol ASIWidget;

@interface ASTextInputLayoutImpl_TextInputLayoutBean : ASViewGroupImpl_ViewGroupBean

#pragma mark Public

- (instancetype)initWithASTextInputLayoutImpl:(ASTextInputLayoutImpl *)outer$;

- (id)getBoxStrokeErrorColor;

- (id)getCounterMaxLength;

- (id)getCounterOverflowTextColor;

- (id)getCounterTextColor;

- (id)getEndIconDrawable;

- (id)getEndIconMode;

- (id)getErrorIconDrawable;

- (id)getHint;

- (id)getHintTextColor;

- (id)getPlaceholderTextColor;

- (id)getPrefixTextColor;

- (id)getStartIconDrawable;

- (id)getSuffixTextColor;

- (void)setBoxBackgroundColorWithNSString:(NSString *)value;

- (void)setBoxBackgroundModeWithNSString:(NSString *)value;

- (void)setBoxCornerRadiusBottomEndWithNSString:(NSString *)value;

- (void)setBoxCornerRadiusBottomStartWithNSString:(NSString *)value;

- (void)setBoxCornerRadiusTopEndWithNSString:(NSString *)value;

- (void)setBoxCornerRadiusTopStartWithNSString:(NSString *)value;

- (void)setBoxPaddingWithNSString:(NSString *)value;

- (void)setBoxStrokeColorWithNSString:(NSString *)value;

- (void)setBoxStrokeErrorColorWithNSString:(NSString *)value;

- (void)setBoxStrokeWidthWithNSString:(NSString *)value;

- (void)setCounterEnabledWithBoolean:(jboolean)value;

- (void)setCounterMaxLengthWithInt:(jint)value;

- (void)setCounterOverflowTextAppearanceWithNSString:(NSString *)value;

- (void)setCounterOverflowTextColorWithNSString:(NSString *)value;

- (void)setCounterTextAppearanceWithNSString:(NSString *)value;

- (void)setCounterTextColorWithNSString:(NSString *)value;

- (void)setEnabledWithBoolean:(jboolean)value;

- (void)setEndIconDrawableWithNSString:(NSString *)value;

- (void)setEndIconModeWithNSString:(NSString *)value;

- (void)setEndIconOnClickWithNSString:(NSString *)value;

- (void)setEndIconOnLongClickWithNSString:(NSString *)value;

- (void)setEndIconVisibleWithBoolean:(jboolean)value;

- (void)setErrorWithNSString:(NSString *)value;

- (void)setErrorEnabledWithBoolean:(jboolean)value;

- (void)setErrorIconDrawableWithNSString:(NSString *)value;

- (void)setErrorIconOnClickWithNSString:(NSString *)value;

- (void)setErrorIconOnLongClickWithNSString:(NSString *)value;

- (void)setErrorTextAppearanceWithNSString:(NSString *)value;

- (void)setErrorTextColorWithNSString:(NSString *)value;

- (void)setHelperTextWithNSString:(NSString *)value;

- (void)setHelperTextColorWithNSString:(NSString *)value;

- (void)setHelperTextEnabledWithBoolean:(jboolean)value;

- (void)setHelperTextTextAppearanceWithNSString:(NSString *)value;

- (void)setHintWithNSString:(NSString *)value;

- (void)setHintEnabledWithBoolean:(jboolean)value;

- (void)setHintTextAppearanceWithNSString:(NSString *)value;

- (void)setHintTextColorWithNSString:(NSString *)value;

- (void)setPlaceholderTextWithNSString:(NSString *)value;

- (void)setPlaceholderTextColorWithNSString:(NSString *)value;

- (void)setPrefixTextWithNSString:(NSString *)value;

- (void)setPrefixTextAppearanceWithNSString:(NSString *)value;

- (void)setPrefixTextColorWithNSString:(NSString *)value;

- (void)setStartIconDrawableWithNSString:(NSString *)value;

- (void)setStartIconOnClickWithNSString:(NSString *)value;

- (void)setStartIconOnLongClickWithNSString:(NSString *)value;

- (void)setStartIconVisibleWithBoolean:(jboolean)value;

- (void)setSuffixTextWithNSString:(NSString *)value;

- (void)setSuffixTextAppearanceWithNSString:(NSString *)value;

- (void)setSuffixTextColorWithNSString:(NSString *)value;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithASIWidget:(id<ASIWidget>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_TextInputLayoutBean)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_TextInputLayoutBean_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl_TextInputLayoutBean *self, ASTextInputLayoutImpl *outer$);

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutBean *new_ASTextInputLayoutImpl_TextInputLayoutBean_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutBean *create_ASTextInputLayoutImpl_TextInputLayoutBean_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_TextInputLayoutBean)

#endif

#if !defined (ASTextInputLayoutImpl_TextInputLayoutParamsBean_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_TextInputLayoutParamsBean))
#define ASTextInputLayoutImpl_TextInputLayoutParamsBean_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupParamsBean 1
#include "ViewGroupImpl.h"

@class ASTextInputLayoutImpl;

@interface ASTextInputLayoutImpl_TextInputLayoutParamsBean : ASViewGroupImpl_ViewGroupParamsBean

#pragma mark Public

- (instancetype)initWithASTextInputLayoutImpl:(ASTextInputLayoutImpl *)outer$;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_TextInputLayoutParamsBean)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_TextInputLayoutParamsBean_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl_TextInputLayoutParamsBean *self, ASTextInputLayoutImpl *outer$);

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutParamsBean *new_ASTextInputLayoutImpl_TextInputLayoutParamsBean_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutParamsBean *create_ASTextInputLayoutImpl_TextInputLayoutParamsBean_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_TextInputLayoutParamsBean)

#endif

#if !defined (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder))
#define ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder_

#define RESTRICT_ViewGroupImpl 1
#define INCLUDE_ASViewGroupImpl_ViewGroupCommandParamsBuilder 1
#include "ViewGroupImpl.h"

@class ASTextInputLayoutImpl;

@interface ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder : ASViewGroupImpl_ViewGroupCommandParamsBuilder

#pragma mark Public

- (instancetype)initWithASTextInputLayoutImpl:(ASTextInputLayoutImpl *)outer$;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)reset;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginBottomWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginEndWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginHorizontalWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginLeftWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginRightWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginStartWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginTopWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginVerticalWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)setLayoutMarginWithNSString:(NSString *)arg0;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)tryGetLayoutMarginBottom;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)tryGetLayoutMarginEnd;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)tryGetLayoutMarginLeft;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)tryGetLayoutMarginRight;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)tryGetLayoutMarginStart;

- (ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *)tryGetLayoutMarginTop;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *self, ASTextInputLayoutImpl *outer$);

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *new_ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder *create_ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_TextInputLayoutCommandParamsBuilder)

#endif

#pragma pop_macro("INCLUDE_ALL_TextInputLayoutImpl")
