//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSTextInputLayoutPlugin\src\main\java\com\ashera\textinputlayout\TextInputLayoutImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TextInputLayoutImpl")
#ifdef RESTRICT_TextInputLayoutImpl
#define INCLUDE_ALL_TextInputLayoutImpl 0
#else
#define INCLUDE_ALL_TextInputLayoutImpl 1
#endif
#undef RESTRICT_TextInputLayoutImpl

#if !defined (ASTextInputLayoutImpl_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl))
#define ASTextInputLayoutImpl_

#define RESTRICT_BaseHasWidgets 1
#define INCLUDE_ASBaseHasWidgets 1
#include "BaseHasWidgets.h"

#define RESTRICT_FormElement 1
#define INCLUDE_ASFormElement 1
#include "FormElement.h"

@class ASWidgetAttribute;
@class IOSClass;
@protocol ASHasWidgets;
@protocol ASIFragment;
@protocol ASILifeCycleDecorator;
@protocol ASIWidget;
@protocol JavaUtilMap;

@interface ASTextInputLayoutImpl : ASBaseHasWidgets < ASFormElement >
@property id uiView;

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithNSString:(NSString *)localname;

- (instancetype)initWithNSString:(NSString *)groupName
                    withNSString:(NSString *)localname;

- (void)addWithASIWidget:(id<ASIWidget>)w
                 withInt:(jint)index;

- (id)asNativeWidget;

- (id)asWidget;

- (jboolean)checkIosVersionWithNSString:(NSString *)v;

- (void)createWithASIFragment:(id<ASIFragment>)fragment
              withJavaUtilMap:(id<JavaUtilMap>)params;

- (void)focus;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
              withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (id)getChildAttributeWithASIWidget:(id<ASIWidget>)w
               withASWidgetAttribute:(ASWidgetAttribute *)key;

- (id<ASHasWidgets>)getCompositeLeafWithASIWidget:(id<ASIWidget>)w;

- (NSString *)getTextEntered;

- (IOSClass *)getViewClass;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (void)invalidate;

- (jboolean)isViewVisible;

- (void)loadAttributesWithNSString:(NSString *)localName;

- (id<ASIWidget>)newInstance OBJC_METHOD_FAMILY_NONE;

- (jboolean)removeWithInt:(jint)index;

- (jboolean)removeWithASIWidget:(id<ASIWidget>)w;

- (void)requestLayout;

- (void)resetError;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)key
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue
                withASILifeCycleDecorator:(id<ASILifeCycleDecorator>)decorator;

- (void)setChildAttributeWithASIWidget:(id<ASIWidget>)w
                 withASWidgetAttribute:(ASWidgetAttribute *)key
                          withNSString:(NSString *)strValue
                                withId:(id)objValue;

- (void)setEndIconInternalWithId:(id)objValue
                     withBoolean:(jboolean)skipConvert;

- (void)setIdWithNSString:(NSString *)id_;

- (void)setVisibleWithBoolean:(jboolean)b;

- (void)showErrorWithNSString:(NSString *)message;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl)

inline NSString *ASTextInputLayoutImpl_get_LOCAL_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTextInputLayoutImpl_LOCAL_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTextInputLayoutImpl, LOCAL_NAME, NSString *)

inline NSString *ASTextInputLayoutImpl_get_GROUP_NAME(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ASTextInputLayoutImpl_GROUP_NAME;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ASTextInputLayoutImpl, GROUP_NAME, NSString *)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_init(ASTextInputLayoutImpl *self);

FOUNDATION_EXPORT ASTextInputLayoutImpl *new_ASTextInputLayoutImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl *create_ASTextInputLayoutImpl_init(void);

FOUNDATION_EXPORT void ASTextInputLayoutImpl_initWithNSString_(ASTextInputLayoutImpl *self, NSString *localname);

FOUNDATION_EXPORT ASTextInputLayoutImpl *new_ASTextInputLayoutImpl_initWithNSString_(NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl *create_ASTextInputLayoutImpl_initWithNSString_(NSString *localname);

FOUNDATION_EXPORT void ASTextInputLayoutImpl_initWithNSString_withNSString_(ASTextInputLayoutImpl *self, NSString *groupName, NSString *localname);

FOUNDATION_EXPORT ASTextInputLayoutImpl *new_ASTextInputLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl *create_ASTextInputLayoutImpl_initWithNSString_withNSString_(NSString *groupName, NSString *localname);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl)

@compatibility_alias ComAsheraTextinputlayoutTextInputLayoutImpl ASTextInputLayoutImpl;

#endif

#if !defined (ASTextInputLayoutImpl_EndIconMode_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_EndIconMode))
#define ASTextInputLayoutImpl_EndIconMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTextInputLayoutImpl_EndIconMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_EndIconMode)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_EndIconMode_init(ASTextInputLayoutImpl_EndIconMode *self);

FOUNDATION_EXPORT ASTextInputLayoutImpl_EndIconMode *new_ASTextInputLayoutImpl_EndIconMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_EndIconMode *create_ASTextInputLayoutImpl_EndIconMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_EndIconMode)

#endif

#if !defined (ASTextInputLayoutImpl_BoxBackgroundMode_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_BoxBackgroundMode))
#define ASTextInputLayoutImpl_BoxBackgroundMode_

#define RESTRICT_AbstractEnumToIntConverter 1
#define INCLUDE_ASAbstractEnumToIntConverter 1
#include "AbstractEnumToIntConverter.h"

@class JavaLangInteger;
@protocol JavaUtilMap;

@interface ASTextInputLayoutImpl_BoxBackgroundMode : ASAbstractEnumToIntConverter

#pragma mark Public

- (JavaLangInteger *)getDefault;

- (id<JavaUtilMap>)getMapping;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_BoxBackgroundMode)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_BoxBackgroundMode_init(ASTextInputLayoutImpl_BoxBackgroundMode *self);

FOUNDATION_EXPORT ASTextInputLayoutImpl_BoxBackgroundMode *new_ASTextInputLayoutImpl_BoxBackgroundMode_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_BoxBackgroundMode *create_ASTextInputLayoutImpl_BoxBackgroundMode_init(void);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_BoxBackgroundMode)

#endif

#if !defined (ASTextInputLayoutImpl_TextInputLayoutExt_) && (INCLUDE_ALL_TextInputLayoutImpl || defined(INCLUDE_ASTextInputLayoutImpl_TextInputLayoutExt))
#define ASTextInputLayoutImpl_TextInputLayoutExt_

#define RESTRICT_LinearLayout 1
#define INCLUDE_ADLinearLayout 1
#include "LinearLayout.h"

#define RESTRICT_ILifeCycleDecorator 1
#define INCLUDE_ASILifeCycleDecorator 1
#include "ILifeCycleDecorator.h"

#define RESTRICT_IMaxDimension 1
#define INCLUDE_ASIMaxDimension 1
#include "IMaxDimension.h"

@class ADContext;
@class ADRect;
@class ADView;
@class ASTextInputLayoutImpl;
@class ASWidgetAttribute;
@class IOSIntArray;
@class IOSObjectArray;
@protocol ASIWidget;
@protocol JavaUtilList;

@interface ASTextInputLayoutImpl_TextInputLayoutExt : ADLinearLayout < ASILifeCycleDecorator, ASIMaxDimension >

#pragma mark Public

- (instancetype)initWithASTextInputLayoutImpl:(ASTextInputLayoutImpl *)outer$;

- (void)drawableStateChanged;

- (void)endViewTransitionWithADView:(ADView *)view;

- (void)executeWithNSString:(NSString *)method
          withNSObjectArray:(IOSObjectArray *)canvas;

- (id)getAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute;

- (void)getLocationOnScreenWithIntArray:(IOSIntArray *)appScreenLocation;

- (jint)getMaxHeight;

- (jint)getMaxWidth;

- (id<JavaUtilList>)getMethods;

- (id<ASIWidget>)getWidget;

- (void)getWindowVisibleDisplayFrameWithADRect:(ADRect *)displayFrame;

- (ADView *)inflateViewWithNSString:(NSString *)layout;

- (void)initialized OBJC_METHOD_FAMILY_NONE;

- (id<ASILifeCycleDecorator>)newInstanceWithASIWidget:(id<ASIWidget>)widget OBJC_METHOD_FAMILY_NONE;

- (void)offsetLeftAndRightWithInt:(jint)offset;

- (void)offsetTopAndBottomWithInt:(jint)offset;

- (void)onMeasureWithInt:(jint)widthMeasureSpec
                 withInt:(jint)heightMeasureSpec;

- (void)remeasure;

- (void)removeFromParent;

- (void)setAttributeWithASWidgetAttribute:(ASWidgetAttribute *)widgetAttribute
                             withNSString:(NSString *)strValue
                                   withId:(id)objValue;

- (void)setMaxHeightWithInt:(jint)height;

- (void)setMaxWidthWithInt:(jint)width;

- (void)setMyAttributeWithNSString:(NSString *)name
                            withId:(id)value;

- (void)setState0WithId:(id)value;

- (void)setState1WithId:(id)value;

- (void)setState2WithId:(id)value;

- (void)setState3WithId:(id)value;

- (void)setState4WithId:(id)value;

- (void)setVisibilityWithInt:(jint)visibility;

- (void)state0;

- (void)state1;

- (void)state2;

- (void)state3;

- (void)state4;

- (void)stateNo;

- (void)stateYes;

- (void)updateMeasuredDimensionWithInt:(jint)width
                               withInt:(jint)height;

#pragma mark Protected

- (void)onLayoutWithBoolean:(jboolean)changed
                    withInt:(jint)l
                    withInt:(jint)t
                    withInt:(jint)r
                    withInt:(jint)b;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithADContext:(ADContext *)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASTextInputLayoutImpl_TextInputLayoutExt)

FOUNDATION_EXPORT void ASTextInputLayoutImpl_TextInputLayoutExt_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl_TextInputLayoutExt *self, ASTextInputLayoutImpl *outer$);

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutExt *new_ASTextInputLayoutImpl_TextInputLayoutExt_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASTextInputLayoutImpl_TextInputLayoutExt *create_ASTextInputLayoutImpl_TextInputLayoutExt_initWithASTextInputLayoutImpl_(ASTextInputLayoutImpl *outer$);

J2OBJC_TYPE_LITERAL_HEADER(ASTextInputLayoutImpl_TextInputLayoutExt)

#endif

#pragma pop_macro("INCLUDE_ALL_TextInputLayoutImpl")
